<?php

namespace AppBundle\Repository;

/**
 * komponentenattributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class komponentenattributeRepository extends \Doctrine\ORM\EntityRepository
{
}
