<?php

namespace AppBundle\Repository;

/**
 * komponente_hat_attributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Komponente_hat_attributeRepository extends \Doctrine\ORM\EntityRepository
{
}
