<?php

namespace AppBundle\Repository;

/**
 * raeumeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class raeumeRepository extends \Doctrine\ORM\EntityRepository
{
}
