<?php

namespace AppBundle\Repository;

/**
 * software_in_raumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class software_in_raumRepository extends \Doctrine\ORM\EntityRepository
{
}
