<?php

namespace AppBundle\Repository;

/**
 * wird_beschrieben_durchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Wird_beschrieben_durchRepository extends \Doctrine\ORM\EntityRepository
{
}
