services:

    AppBundle\Service\KomponentenSucheService:
        class: AppBundle\Service\KomponentenSucheService
        arguments:
            - "@doctrine.orm.entity_manager"
    AppBundle\Service\verschiebeCompService:
        class: AppBundle\Service\verschiebeCompService
        arguments:
            - "@doctrine.orm.entity_manager"
