AppBundle\Entity\Komponente_hat_attribute:
    type: entity
    table: komponente_hat_attribute
    repositoryClass: AppBundle\Repository\Komponente_hat_attributeRepository
    id:
        komponentenattributeId:
            associationKey: true
        komponentenId:
            associationKey: true

    fields:
        wert:
            type: string
            length: '45'
    manyToOne:
        komponentenattributeId:
            targetEntity: Komponentenattribute
            joinColumn:
                name: komponentenattribute_Id
                referencedColumnName: id
        komponentenId:
            targetEntity: Komponenten
            joinColumn:
                name: komponenten_Id
                referencedColumnName: id

