AppBundle\Entity\Komponentenattribute:
    type: entity
    table: komponentenattribute
    repositoryClass: AppBundle\Repository\KomponentenattributeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        bezeichnung:
            type: string
            length: '25'
    oneToMany:
        komponentenattribute_hat:
            targetEntity: Komponente_hat_attribute
            mappedBy: komponentenattributeId
    manyToMany:
        komponentenarten:
            targetEntity: Komponentenarten
            inversedBy: komponentenattribute
            joinTable:
                name: wird_beschrieben_durch
                JoinColumns:
                    komponentenattribut_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    komponentenarten_id:
                        referencedColumnName: id
