AppBundle\Entity\komponentenattribute:
    type: entity
    table: komponentenattribute
    repositoryClass: AppBundle\Repository\komponentenattributeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        bezeichnung:
            type: string
            length: '25'
    oneToMany:
        komponentenattribute_hat:
            targetEntity: komponente_hat_attribute
            mappedBy: komponentenattributeId
        komponentenattribute_beschr:
            targetEntity: wird_beschrieben_durch
            mappedBy: komponentenattributeId