AppBundle\Entity\Komponentenarten:
  type:  entity
  table: komponentenarten
  id:
      id:
          type: integer
          generator: { strategy: auto }
  fields:
      komponentenart:
          type: string
          legnth: 45
  oneToMany:
      komponenten:
          targetEntity: Komponenten
          mappedBy: komponentenarten_id
  manyToMany:
      komponentenattribute:
          targetEntity: Komponentenattribute
          mappedBy: komponentenarten
          cascade: [persist]
