AppBundle\Entity\komponente_hat_attribute:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\komponente_hat_attributeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        komponentenId:
            type: integer
            column: komponenten_id
        komponentenattributeId:
            type: integer
            column: komponentenattribute_id
        wert:
            type: string
            length: '45'
    lifecycleCallbacks: {  }
