AppBundle\Entity\raeume:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\raeumeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        Nr:
            type: string
            length: '20'
            column: nr
        Bezeichnung:
            type: string
            length: '45'
            column: bezeichnung
        Notiz:
            type: string
            length: '255'
            column: notiz
