AppBundle\Entity\raeume:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\raeumeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        rId:
            type: integer
            unique: true
            column: r_id
        rNr:
            type: text
            column: r_nr
        rBezeichnung:
            type: text
            column: r_bezeichnung
        rNotiz:
            type: text
            column: r_notiz
    lifecycleCallbacks: {  }
