AppBundle\Entity\Raeume:
    type: entity
    table: raeume
    repositoryClass: AppBundle\Repository\RaeumeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        Nr:
            type: string
            length: '20'
            column: nr
        Bezeichnung:
            type: string
            length: '45'
            column: bezeichnung
        Notiz:
            type: string
            length: '255'
            column: notiz
            nullable: TRUE
    oneToMany:
        raeume:
            targetEntity: Komponenten
            mappedBy: raeume_id
        software_in_raum:
            targetEntity: Software_in_raum
            mappedBy: raeumeId
