AppBundle\Entity\software_in_raum:
    type: entity
    table: software_in_raum
    repositoryClass: AppBundle\Repository\software_in_raumRepository
    fields:
        komponentenId:
            type: integer
            column: komponenten_id
        raeumeId:
            type: integer
            column: raeume_id
    manyToOne:
      raeume_id:
          targetEntity: raeume
          inversedBy: software_in_raum
          joinColumn:
              name: raeumeId
              referencedColumnName: id 
      komponenten_id:
          targetEntity: raeume
          inversedBy: software_in_raum
          joinColumn:
              name: komponentenId
              referencedColumnName: id 
        