AppBundle\Entity\Software_in_raum:
    type: entity
    table: software_in_raum
    repositoryClass: AppBundle\Repository\Software_in_raumRepository
    id:
        komponentenId:
            associationKey: true
        raeumeId:
            associationKey: true
    manyToOne:
      raeumeId:
          targetEntity: Raeume
          inversedBy: software_in_raum
          joinColumn:
              name: raeume_Id
              referencedColumnName: id 
      komponentenId:
          targetEntity: Komponenten
          inversedBy: software_in_raum
          joinColumn:
              name: komponenten_Id
              referencedColumnName: id 
