AppBundle\Entity\Wird_beschrieben_durch:
    type: entity
    table: wird_beschrieben_durch
    repositoryClass: AppBundle\Repository\Wird_beschrieben_durchRepository
    id:
        komponentenattributId:
            associationKey: true
        komponentenartenId:
            associationKey: true
    manyToOne:
      komponentenattributId:
        targetEntity: Komponentenattribute
        inversedBy: komponentenattribute_beschr
        joinColumn:
          name: komponentenattribute_id
          referencedColumnName: id
      komponentenartenId:
        targetEntity: Komponentenarten
        inversedBy: wirdBeschriebenDurch
        joinColumn:
          name: komponentenarten_id
          referencedColumnName: id
