AppBundle\Entity\wird_beschrieben_durch:
    type: entity
    table: wird_beschrieben_durch
    repositoryClass: AppBundle\Repository\wird_beschrieben_durchRepository
    manyToOne:
      komponentenattribute:
        targetEntity: komponentenattribute
        joinColumn:
          name: komponentenattributeId
          referencedColumnName: id
      komponentenartid:
        targetEntity: komponentenarten
        joinColumn:
          name: komponentenartId
          referencedColumnName: id