AppBundle\Entity\wird_beschrieben_durch:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\wird_beschrieben_durchRepository
    manyToOne:
    komponentenattribute:
      targetEntity: komponentenattribute
      joinColumn:
        name: komponentenattributeId
        referencedColumnName: id
    komponentenartid:
      targetEntity: komponentenart
      joinColumn:
        name: komponentenartId
        referencedColumnName: id